# Generated by Django 2.2 on 2021-03-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0006_auto_20210320_1621'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='advertisement',
            table='advertisements',
        ),
    ]
