# Generated by Django 2.2 on 2021-03-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0007_auto_20210320_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['title']},
        ),
    ]
